[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32-s3

monitor_speed = 115200

lib_deps =
  ESP32Servo
  https://github.com/sparkfun/SparkFun_VL53L4CD_Arduino_Library.git

build_flags =
  -DUSE_SPARKFUN_VL53L4CD
